### ISSUE TITLE
Parsing an image with a malformed registry URL causes high CPU usage

### ISSUE THREAD

**Issue by orf** [realityone/docker-image-py#3]
Running this code:

```
from docker_image import reference
reference.Reference.parse('123.dkr.ecr.eu-west-1.amazonaws.com:lol/abc:d')
```

It seems to hang, and CPU usage goes up.

Edit: Sorry, I wasn't clear. This is an invalid reference, but it ideally shouldn't cause a system to hang and experience CPU spikes if parsed.

**Comment by realityone** [comment]
Thanks for reporting.

I will check this later.

**Comment by realityone** [comment]
Hi @orf ,

I guess the high CPU usage is caused by regex package with some complicate pattern, I will digging this later.

Validating the hostname manually can solved issue temporary in this [PR](https://github.com/realityone/docker-image-py/pull/4/files) .
