### ISSUE TITLE
split_hostname returns wrong hostname for custom images

### ISSUE THREAD

**Issue by dvdgsng** [realityone/docker-image-py#5]
When parsing _custom images_ (format: `$user/$image`) from the default registry (docker hub), `split_hostname()` returns the user name as registry hostname.

Example:
```python
>>> from docker_image import reference
>>> ref = reference.Reference.parse('containous/traefik')
>>> ref.split_hostname()
('containous', 'traefik')
```

**Comment by realityone** [comment]
Hi @dvdgsng ,

This maybe caused by distribution separate the `reference` and the `fully qualified reference`,
I will fix this later.

**Comment by MrCreosote** [comment]
This seems to still be an issue in 0.1.13:

```python
In [29]: parsed = reference.Reference.parse("containous/traefik")

In [30]: parsed.split_hostname()
Out[30]: ('containous', 'traefik')
```
